name: oyt_front_restaurant
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/nestorsgarzonc
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  oyt_front_core:
    path: ../oyt_front_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
